### ISSUE TITLE
Didn't find `makeImports()` in `XRtools`

### ISSUE THREAD

**Issue by xhdong-umd** [johnmchambers/XRtools#1]
I read in the book `Extending R` that there is a function `makeImports()` in `XRtools`. I'm interested in this function and want to see if it can help on Shiny package dependency management. 

However I can't find this function in the package help or this github repo. I tried to install `XRtools` from CRAN but it was built for R 3.3.3.

Is there something I missed, or the function is not released yet?

**Comment by johnmchambers** [comment]
Yes, sorry, that file was in the wrong place and didn’t make it into the package.

It has been added to the github version.  No documentation yet, so not ready for CRAN  (CRAN updates are lagging behind, I’m afraid.)

Thanks for the alert.

On May 19, 2017, at 5:51 AM, xianghui dong <notifications@github.com<mailto:notifications@github.com>> wrote:


I read in the book Extending R that there is a function makeImports() in XRtools. I'm interested in this function and want to see if it can help on Shiny package dependency management.

However I can't find this function in the package help or this github repo. I tried to install XRtools from CRAN but it was built for R 3.3.3.

Is there something I missed, or the function is not released yet?

**Comment by xhdong-umd** [comment]
Thanks for the quick update!

I used it on my packages [namebrowser](https://github.com/dracodoc/namebrowser) and [mischelper](https://github.com/dracodoc/mischelper) and found some corner cases didn't get processed correctly.

```r
> makeImports("mischelper")
## Not found: depth, `item_class`, `row_no`, type, value, `value_class` 
## Found, but not in package: View 
importFrom(base, .I) 
importFrom(stats, line) 
importFrom(utils, capture.output, str) 
```

- `data.table` have some special syntax that will be reported by `codetools::findGlobals` incorrectly.

```r
library(data.table)
fun <- function() {
  dt <- data.table(1:26, letters)
  dt[, row_no := .I]  # row_no is an new column defined by .I which is row index
}

> codetools::findGlobals(fun)
[1] ":"          ":="         ".I"         "["          "{"          "<-"         "data.table"
[8] "letters"    "row_no"   
```

  Here `row_no` is an new column defined in place, without quotes in `data.table syntax`. `.I` is a special symbol in `data.table`.

`.I` in `data.table` was also reported from `base`. I'm not sure how this happened.

```r
> pkgOf(".I")
[1] "base"
```

  `data.table` is different from regular R packages in many ways. Using `data.table` in package need explicit import instructions, so it's unlikely the package developer haven't done it and I don't think they need `makeImport` to check on this part. But there could be lots of new column names reported in `makeImport` which will confuse the user.

I'm not sure how to fix this since it seemed to be difficult.

- RStudio have a `View` function which will not be find with code `packageName(environment(View))` because 

```r
> environment(View)
<environment: 0x108418ad8>
```

It may come from [tool:rstudio](https://github.com/rstudio/rstudio/blob/master/src/cpp/r/R/Tools.R#L17) but I didn't find it in that code. Anyway it's something in RStudio.

**Comment by johnmchambers** [comment]
Some documentation has been added that may be relevant.

In particular, nothing in the current code to deal with problems in findGlobals().

More of an issue to me than the examples you mention is that the code will not deal with the
package::function syntax, which is a style I (and others) would strongly recommend whenever there is any question about finding references.

Like most of XRtools, this was a fairly quick-and-dirty implementation.  Patches very welcome!

**Comment by dracodoc** [comment]
I found sometimes I need to convert existing code into a package, and I need to find all external functions and add the proper package prefix. `makeImport` is intended for different usage but the source code helped me to get [my solution](https://github.com/dracodoc/mischelper). 

I think the issue should also be closed now. Thanks!

**Comment by xhdong-umd** [comment]
I found sometimes I need to convert existing code into a package, and I need to find all external functions and add the proper package prefix. makeImport is intended for different usage but the source code helped me to get [my solution](https://github.com/dracodoc/mischelper).

I think the issue should also be closed now. Thanks!
